Allow-for-Superuser-deletion
silverlogic/baseapp-backend pull request #104
Opened 2024-04-19 18:59 UTC by MattGalvis

2024-04-22 12:59 UTC, nossila commented
@MattGalvis you need to increase the version in setup.cfg in that package if you want that released in pypi soon

2024-04-30 15:31 UTC, Janekk approved these changes

2024-05-01 01:53 UTC, nossila requested changes
We need to have a custom base [Event model](https://django-pghistory.readthedocs.io/en/3.2.0/settings/#pghistory_base_model) in `baseapp-core`  to not break compatibility on projects [using our fork](https://github.com/Opus10/django-pghistory/pull/69/files)

2024-05-22 19:40 UTC, nossila approved these changes

2024-05-23 12:55 UTC, merged