[WIP]
silverlogic/baseapp-backend pull request #109
Opened 2024-05-09 17:07 UTC by vitorguima

2024-05-14 14:07 UTC, vitorguima commented
[] missing Readme

2024-05-18 13:01 UTC, nossila requested changes

2024-05-18 13:01 UTC, nossila commented on baseapp-ratings/baseapp_ratings/models.py
> +    target_object_id = models.PositiveIntegerField(blank=True, null=True, db_index=True)
I think we can remove the `db_index` here as well, I see no reason to filter only by `target_object_id` and not use `target_content_type` in the filter

2024-05-20 12:47 UTC, vitorguima commented on baseapp-auth/baseapp_auth/graphql/object_types.py
> +    interfaces += (RatingsInterface,)
yes

2024-05-20 15:58 UTC, vitorguima commented on baseapp-ratings/baseapp_ratings/admin.py
> +        "user",
done

2024-05-20 15:58 UTC, vitorguima commented on baseapp-ratings/baseapp_ratings/graphql/object_types.py
> +        node = super().get_node(info, id)
done

2024-05-20 15:59 UTC, vitorguima commented on baseapp-ratings/baseapp_ratings/graphql/mutations.py
> +            content_type = ContentType.objects.get_for_model(target)
done

2024-05-20 15:59 UTC, vitorguima commented on baseapp-ratings/baseapp_ratings/graphql/object_types.py
> +    my_reaction = graphene.Field(lambda: RatingObjectType, required=False)
done

2024-05-20 15:59 UTC, vitorguima commented on baseapp-ratings/baseapp_ratings/graphql/object_types.py
> +        if not CAN_ANONYMOUS_VIEW_REACTIONS and not info.context.user.is_authenticated:
done

2024-06-12 02:07 UTC, nossila approved these changes

2024-07-18 14:31 UTC, merged