BA-1097-Django-Cloudflare-Stream-Package-to-BA-BE
silverlogic/baseapp-backend pull request #14
Opened 2023-07-18 17:56 UTC by MattGalvis

2023-07-18 21:02 UTC, pablogadhi commented on baseapp-cloudflare-stream-field/testproject/__init__.py
Aren't we missing the wsgi configuration for the testproject @MattGalvis ? Could run it just fine after adding it.

2023-07-19 19:07 UTC, Janekk requested changes

2023-07-19 19:07 UTC, Janekk commented on baseapp-cloudflare-stream-field/testproject/wsgi.py
> +"""
can we delete bec there is such file on `baseapp-core`?

2023-07-19 19:07 UTC, Janekk commented on baseapp-cloudflare-stream-field/pyproject.toml
> +[build-system]
```
[tool.black]
...
[tool.isort]
...
```
sections are already in the root dir `baseapp-backend/pyproject.toml` and CI uses that one, so maybe just leave `[build-system]` section?

2023-07-20 12:28 UTC, dpTsl approved these changes

2023-07-20 12:37 UTC, dpTsl commented
Hey, Matt! That is not related to your PR but could you please rename the jobs to follow a pattern?
I think we can remove "workflow" from [baseapp-core-workflow](https://github.com/silverlogic/baseapp-backend/pull/14/files#diff-d8485ae5feb85d5310fbb669eca158cacafdba09b695a16d47720b69b9072e23R10)", from [baseapp-auth-workflow](https://github.com/silverlogic/baseapp-backend/pull/14/files#diff-d8485ae5feb85d5310fbb669eca158cacafdba09b695a16d47720b69b9072e23R14) and also from the [comment](https://github.com/silverlogic/baseapp-backend/pull/14/files#diff-d8485ae5feb85d5310fbb669eca158cacafdba09b695a16d47720b69b9072e23R38).

And I think that we could also remove the [baseapp-reactions comment](https://github.com/silverlogic/baseapp-backend/pull/14/files#diff-d8485ae5feb85d5310fbb669eca158cacafdba09b695a16d47720b69b9072e23R22)

2023-07-20 12:41 UTC, Janekk approved these changes

2023-07-20 12:53 UTC, merged