BA-1945: MFA Follow Up | Sign Up Welcome Email
silverlogic/baseapp-backend pull request #202
Opened 2024-12-12 17:33 UTC by luisguareschi

Original Story:  
Acceptance Criteria 

Implementing AllAuth broke the welcome email on signup

Make sure send_welcome_email gets called on user sign up 

Current behavior 

Expected behavior 

Code Snippet 

Notes 

Please work in the feature/allauth branch

The same person that tackles the extra params story should take this one. The initial research is similar.
Check: https://docs.allauth.org/en/latest/common/email.html 

Approvd 
https://app.approvd.io/projects/BA/stories/36946

2024-12-13 14:09 UTC, patsluth approved these changes

2024-12-13 18:18 UTC, priscilladeroode commented
Please, fix the lint @luisguareschi

2024-12-13 18:20 UTC, priscilladeroode requested changes
Please, fix the lint @luisguareschi

2024-12-16 11:44 UTC, anicioalexandre commented on baseapp-auth/baseapp_auth/templates/users/emails/welcome-body.html.j2
@nossila @nick-prat  shouldn't we use the baseapp-message-templates package for the email templates?

2024-12-16 12:08 UTC, luisguareschi commented on baseapp-auth/baseapp_auth/templates/users/emails/welcome-body.html.j2
@anicioalexandre I used the same template that was already being used by the send_welcome_email function so I think it should be okay like this right?

2024-12-16 16:43 UTC, patsluth-tsl approved these changes

2024-12-19 14:12 UTC, vitorguima approved these changes

2024-12-19 14:20 UTC, vitorguima commented on baseapp-auth/baseapp_auth/templates/users/emails/welcome-body.html.j2
honestly since this is going to be merged to BA-1945-be-baseapp-mfa-sign-up-email which is a monster PR. I rather have future stories to fix it in order to do not make this a blocker right now. any thoughts? @anicioalexandre @nick-prat @nossila

2024-12-19 14:32 UTC, nick-prat approved these changes

2024-12-19 18:20 UTC, nossila approved these changes

2024-12-19 19:14 UTC, merged