BA-1085: Initiate baseapp-auth
silverlogic/baseapp-backend pull request #5
Opened 2023-07-07 12:45 UTC by Janekk

2023-07-11 17:39 UTC, nossila requested changes

2023-07-11 17:39 UTC, nossila commented on baseapp-auth/baseapp_auth/baseapp_referrals
this symlink needs to be relative I think

2023-07-11 17:39 UTC, nossila commented on baseapp-auth/testproject/tests/fixtures.py
Most of this fixtures are on baseapp_core already, you could import it from there instead, so we don't have duplicated code

2023-07-11 17:39 UTC, nossila commented on baseapp-auth/testproject/tests/helpers.py
same as this helpers, its on baseapp_core

2023-07-11 17:39 UTC, nossila commented on baseapp-auth/testproject/tests/integration/test_migration_health_check.py
this is also part of baseapp_core

2023-07-11 17:39 UTC, nossila commented on baseapp-auth/testproject/tests/mixins.py
this as well, part of baseapp_core

2023-07-11 17:39 UTC, nossila commented on baseapp-auth/testproject/tests/unit/test_celery_beat_health_check.py
this as well, part of baseapp_core

2023-07-11 17:39 UTC, nossila commented on baseapp-core/baseapp_core/settings/env.py
this also belongs in baseapp_core in my opinion, but its not there yet

2023-07-11 17:56 UTC, nossila commented on baseapp-core/baseapp_core/tests/fixtures.py
> +import testproject.tests.factories as f
I think this can break for projects importing fixtures from this file, I think it shouldn't import factories from the testproject here

2023-07-11 18:04 UTC, nossila commented on baseapp-auth/manage.py
I think this should be moved into the testproject

2023-07-11 20:33 UTC, pablogadhi approved these changes
Tested the JWT flow and decoded the token to see the data. It's looking awesome!
![image](https://github.com/silverlogic/baseapp-backend/assets/22454924/8c398e53-f47f-4e6b-8162-cac530d4a617)

2023-07-11 20:33 UTC, pablogadhi commented on baseapp-auth/baseapp_auth/rest_framework/register/serializers.py
> +from baseapp_referrals.models import UserReferral
Something for the future, but I think we should decouple this module from any logic on the referrals module.

2023-07-12 10:49 UTC, Janekk commented on baseapp-auth/baseapp_auth/baseapp_referrals
resolved in https://github.com/silverlogic/baseapp-backend/pull/5/commits/603909e8d691bcc96c5ad30dd9ffabf6f1c403c1

2023-07-12 20:35 UTC, nossila approved these changes

2023-07-13 11:39 UTC, merged