baseapp-backend-push-notifications
silverlogic/baseapp-backend pull request #57
Opened 2024-01-08 17:02 UTC by vitorguima

2024-01-10 00:37 UTC, nossila requested changes
Would be nice to add a section to `README` about how to setup push notifications.

2024-01-10 00:37 UTC, nossila commented on baseapp-notifications/baseapp_notifications/tasks.py
>      pass
You can remove `pass` here

2024-01-10 00:37 UTC, nossila commented on baseapp-notifications/setup.cfg
Increase the `version` to `0.1.4`

2024-01-11 20:13 UTC, nossila requested changes

2024-01-11 20:13 UTC, nossila commented on baseapp-notifications/baseapp_notifications/utils.py
> +        send_push_notification(
revert this
```suggestion
        send_push_notification.delay(
```

2024-01-11 20:13 UTC, nossila commented on baseapp-notifications/baseapp_notifications/utils.py
> +        kwargs.pop("level", None)
maybe we can do this pop inside the `send_push_notification` function?

2024-01-11 20:13 UTC, nossila commented on baseapp-notifications/baseapp_notifications/utils.py
> +            push_title=push_title,
I think `push_title` could be something like this:

```suggestion
            push_title=push_title or settings.MOBILE_APP_NAME,
```

I noticed this as pattern, when a title is not set it uses the APP_NAME... or iOS and Android already handle this when we sent an empty or None title?

2024-01-23 13:36 UTC, vitorguima commented on baseapp-notifications/baseapp_notifications/tasks.py
> +    push_title = kwargs.pop("push_title", None)
move it to definition params

2024-01-25 14:16 UTC, nossila approved these changes

2024-01-25 14:17 UTC, nossila approved these changes

2024-01-25 17:04 UTC, merged