Change github actions to use docker compose instead
silverlogic/baseapp-backend pull request #68
Opened 2024-01-26 15:30 UTC by nossila

2024-01-26 15:44 UTC, ficast approved these changes

2024-01-26 16:57 UTC, Janekk commented
I guess we should update the [How to develop](https://github.com/silverlogic/baseapp-backend?tab=readme-ov-file#how-to-develop) section of README

2024-01-26 16:58 UTC, Janekk requested changes
I guess we should update the [How to develop](https://github.com/silverlogic/baseapp-backend?tab=readme-ov-file#how-to-develop) section of README

2024-01-28 19:15 UTC, nossila commented
@Janekk updated README, now it suggests using `docker compose` for everything

2024-01-29 12:04 UTC, Janekk approved these changes

2024-01-29 12:29 UTC, merged