BA-1103-Django-View-Action-Permissions-Package-to-BA-BE
silverlogic/baseapp-backend pull request #8
Opened 2023-07-13 16:19 UTC by MattGalvis

```
Acceptance Criteria 
Django View Action Permissions Package to BA BE

move repo below to BA mono-repo

https://bitbucket.org/silverlogic/baseapp-view-action-permissions-django/src/master/

include git history

ensure CI is running for the new project
```

2023-07-13 17:53 UTC, nossila requested changes
@MattGalvis just a few changes so we can follow the same pattern across all packages, take a look at [baseapp-auth](https://github.com/silverlogic/baseapp-backend/tree/master/baseapp-auth) for inspiration, but basically:

move baseapp-email-templates/tests to baseapp-email-templates/baseapp_email_templates/tests this will make the tests part of the package and they would (if wanted) be also executed in the context of your project.

and have a testproject folder in baseapp-email-templates/testproject with all the django project related settings and files, but no actual tests

2023-07-13 17:53 UTC, nossila commented on baseapp-drf-view-action-permissions/testproject/tests/fixtures.py
this is not needed because it exists in baseapp_core, where you use Client you can import from baseapp_core like `from baseapp_core.tests.fixtures import Client`

2023-07-13 17:53 UTC, nossila commented on baseapp-drf-view-action-permissions/testproject/tests/helpers.py
this helpers are also needed because its already in baseapp_core, in your tests where you use helpers like: `from . import helpers as h` you can import them from baseapp_core instead like `from baseapp_core.tests import helpers as h`

2023-07-13 22:07 UTC, nossila approved these changes

2023-07-17 14:08 UTC, rafaelhdr reviewed
Just added a couple comments

2023-07-17 14:08 UTC, rafaelhdr commented on baseapp-drf-view-action-permissions/baseapp_drf_view_action_permissions/models.py
> +    created_at = models.DateTimeField(auto_now_add=True)
Maybe can use `from model_utils.models import TimeStampedModel` instead of doing this by yourself?

2023-07-18 22:03 UTC, pablogadhi approved these changes

2023-07-19 11:49 UTC, dpTsl commented on README.md
> +## Tests
@Janekk updated this title to `how to develop`. Maybe let's keep it?
```suggestion
## How to develop
```

2023-07-19 11:49 UTC, dpTsl commented on baseapp-auth/baseapp_auth/migrations/0004_auto_20230718_1047.py
I'm not sure if we need this migration :thinking: 
Remove this migration?

2023-07-19 11:49 UTC, dpTsl commented on baseapp-drf-view-action-permissions/testproject/settings.py
> +"""
I think we could remove this comment from this file
```suggestion
```

2023-07-19 11:49 UTC, dpTsl commented on baseapp-drf-view-action-permissions/testproject/settings.py
> +]
Reuse as much as possible middlewares from core/tests/settings
```suggestion
MIDDLEWARE += [
    "baseapp_drf_view_action_permissions.middleware.RestrictIpMiddleware",
]
```

2023-07-19 11:49 UTC, dpTsl commented on baseapp-drf-view-action-permissions/testproject/settings.py
> +]
It is exactly the same of core/tests/settings
```suggestion
```

2023-07-19 12:24 UTC, Janekk approved these changes

2023-07-19 15:27 UTC, merged