BA-1104-Django-Email-Templates-Package-to-BA-BE
silverlogic/baseapp-backend pull request #9
Opened 2023-07-13 17:13 UTC by MattGalvis

```
Django Email Templates Package to BA BE

move repo below to BA mono-repo

https://bitbucket.org/silverlogic/baseapp-email-templates-django/src/master/

include git history

ensure CI is running for the new project 
```

2023-07-13 17:38 UTC, nossila requested changes
@MattGalvis just a few changes so we can follow the same pattern across all packages, take a look at [baseapp-auth](https://github.com/silverlogic/baseapp-backend/tree/master/baseapp-auth) for inspiration, but basically:

move `baseapp-email-templates/tests` to `baseapp-email-templates/baseapp_email_templates/tests` this will make the tests part of the package and they would (if wanted) be also executed in the context of your project.

and have a `testproject` folder in `baseapp-email-templates/testproject` with all the django project related settings and files, but no actual tests

2023-07-13 17:58 UTC, nossila requested changes

2023-07-13 17:58 UTC, nossila commented on baseapp-email-templates/tests/fixtures.py
you don't need this file because `outbox` fixture is already on baseapp_core, lets use it from there instead `from baseapp_core.test.fixtures import *`

2023-07-13 17:58 UTC, nossila commented on baseapp-email-templates/tests/conftest.py
> +from tests.fixtures import *  # noqa
import fixtures from baseapp_core here so you don't need to import them in your test files

```suggestion
from baseapp_core.test.fixtures import *  # noqa
```

2023-07-13 22:07 UTC, nossila approved these changes

2023-07-17 14:12 UTC, rafaelhdr approved these changes

2023-07-19 11:57 UTC, dpTsl commented on baseapp-auth/baseapp_auth/migrations/0004_auto_20230718_1047.py
Remove migration?

2023-07-19 11:57 UTC, dpTsl commented on baseapp-drf-view-action-permissions/testproject/requirements.txt
> +django-ipware==4.0.2
We can remove django-ipware

2023-07-19 11:57 UTC, dpTsl commented on baseapp-drf-view-action-permissions/testproject/settings.py
Adjust to reuse core/tests/settings as much as possible

2023-07-19 12:23 UTC, Janekk requested changes

2023-07-19 15:39 UTC, dpTsl approved these changes

2023-07-19 15:44 UTC, Janekk approved these changes

2023-07-19 16:18 UTC, merged